apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-client-a
  namespace: monitoring
  labels:
    app: fl-client
    fl-client-id: client-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-client
      fl-client-id: client-a
  template:
    metadata:
      labels:
        app: fl-client
        fl-client-id: client-a
        role: federated-client
    spec:
      containers:
        - name: fl-client
          image: kanathipz/test-client:0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: CLIENT_ID
              value: "client-a"
            - name: ROUNDS
              value: "15"
            - name: SLEEP_BETWEEN_RUNS
              value: "10"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
