apiVersion: apps/v1
kind: Deployment
metadata:
  name: supernode-1
  namespace: flwr
  labels:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/component: supernode
    app.kubernetes.io/instance: "1"
    app: supernode # <-- เพิ่ม
    role: supernode # <-- เพิ่ม
    fl_client_id: "1" # <-- เพิ่ม
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: supernode
      app.kubernetes.io/component: supernode
      app.kubernetes.io/instance: "1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supernode
        app.kubernetes.io/component: supernode
        app.kubernetes.io/instance: "1"
        app: supernode # <-- เพิ่ม
        role: supernode # <-- เพิ่ม
        fl_client_id: "1" # <-- เพิ่ม
    spec:
      containers:
        - name: supernode
          image: flwr/supernode:1.22.0
          args:
            - --insecure
            - --superlink=superlink:9092
            - --node-config=partition-id=1 num-partitions=2
            - --clientappio-api-address=0.0.0.0:9095
            - --isolation=process
          ports:
            - containerPort: 9095
